apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qryn
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  rules:
    - host: {{ required "hostname for the qryn endpoint" .Values.grafana.hostname }}
      http:
        paths:
        - backend:
            service:
              name: qryn
              port: 
                number: 3100
          path: /
          pathType: Prefix
