apiVersion: v2
name: qryn
version: 2.1.0
description: qryn polyglot observability stack
home: https://qryn.dev
keywords:
  - observability 
  - monitoring 
  - logs
  - metrics
  - tracing
maintainers: 
  - name: Lorenzo Mangani
    email: lorenzo.mangani@gmail.com
sources: 
  - https://github.com/metrico/helm-charts
